version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network  # Use a simpler declaration for networks

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BankDB
      MYSQL_USER: vijay
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - my-network  # Use a simpler declaration for networks

networks:
  my-network:
    driver: bridge